# BlockVillagerTrades Config File

# mode property specifies how to handle items from blocked-items. 
# "block" set maxUses for item to 0
# "remove" removes the trade completely. WARNING: This will delete trades permanently and not restore them when the item is removed from the blocked list.
mode: block

blocked-items:
  # # you can block items by their material name
  # - EMERALD
  # - ENCHANTED_BOOK:
  #     # you can also block specific enchantments on items
  #     enchantments:
  #       # if no level is specified, all levels of the enchantment are blocked
  #       - MENDING
  #       # also you can specify levels
  #       - UNBREAKING: 3
  #       - EFFICIENCY: 4
  #       - EFFICIENCY: 5
  # - DIAMOND_PICKAXE:
  #     enchantments:
  #       - SILK_TOUCH
  #       - LOOTING: 3
  # - DIAMOND_AXE
  # - DIAMOND_SHOVEL
  # - DIAMOND_SWORD